### ISSUE TITLE
"Unnecessarily namespaced ctl script" – questionable check

### ISSUE THREAD

**Issue by voelzmo** [cppforlife/bosh-lint#1]
I don't agree with the "Unnecessarily namespaced ctl script". Many people (e.g. also cf-release) use scripts with PID helpers, such as https://github.com/cloudfoundry/cf-release/blob/master/src/common/utils.sh#L4-L5 which use the script's name in log output and for other things.

**Comment by cppforlife** [comment]
@voelzmo unfortunate, but i think we need to find a better approach then double namespacing entire world.
