### ISSUE TITLE
warn against provides/consumes not inside jobs

### ISSUE THREAD

**Issue by drnic** [cppforlife/bosh-lint#4]
There exists bosh users who get dazed and confused staring at YAML all day. Sometimes they put `consumes:` or `provides:` inside the `/instance_groups/name=abc`, rather than the `/instance_groups/name=abc/jobs/name=xyz`. Help these ppl.

**Comment by cppforlife** [comment]
Done thru https://github.com/cppforlife/bosh-lint/blob/master/src/github.com/cppforlife/bosh-lint/manifest/ig_links.go
