### ISSUE TITLE
JobPropertySecret check has false positives

### ISSUE THREAD

**Issue by jmcarp** [cppforlife/bosh-lint#8]
The `JobPropertySecret` check simply checks whether the property name contains `password`, `passphrase`, etc. But some properties that contain those strings aren't sensitive and can have safe defaults, like `uaa.password.policy.minLength`: https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L312-L314. Would it be possible to whitelist properties as non-sensitive to avoid false positives?

**Comment by rogeruiz** [comment]
looks like they moved it over to https://github.com/cloudfoundry/uaa-release/blob/develop/jobs/uaa/spec#L322-L324

**Comment by cppforlife** [comment]
Seems like now you can use https://github.com/cppforlife/bosh-lint/blob/ac2b068e3e89723a71ee21adb7c12d71337a6830/src/github.com/cppforlife/bosh-lint/release/config.go#L48
